import Head from 'next/head';
import HomePage from '@/components/page/Home';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage />
    </div>
  );
};

export default Home;
